POST localhost:9871/verify/personal
Content-Type: application/json

# "sortCode": "207102", "accountNumber": "44344655" , "name" : "Teddy Dickson" -----> OK
{
  "account" : {
    "sortCode" : "207102",
    "accountNumber" : "44311655"
  },
  "subject" : {
    "name" : "Teddy Dickson"
  }
}
###

POST localhost:9871/verify/personal
Content-Type: application/json

# "sortCode": "207102", "accountNumber": "44344655" , "name" : "Teddy Bear" -----> "nameMatches": "no"
{
  "account" : {
    "sortCode" : "207102",
    "accountNumber" : "44311655"
  },
  "subject" : {
    "name" : "Teddy Bear"
  }
}

###

POST localhost:9871/verify/personal
Content-Type: application/json

# "sortCode": "207102", "accountNumber": "76523611", "companyName" : "Boneféte Fun" -----> "accountNumberIsWellFormatted": "indeterminate"
{
  "account": {
    "sortCode": "609593",
    "accountNumber": "44311611"
  },
  "subject" : {
    "name" : "Teddy Dickson"
  }
}

###

POST localhost:9871/verify/personal
Content-Type: application/json

# "sortCode": "207102", "accountNumber": "76523611", "companyName" : "Boneféte Fun" -----> "sortCodeIsPresentOnEISCD": "no"
{
  "account": {
    "sortCode": "309696",
    "accountNumber": "44333611"
  },
  "subject" : {
    "name" : "Teddy Dickson"
  }
}

###
